### PR TITLE
added issues

### PR DESCRIPTION
**Pull request by NK-Works**
Closes: #2

please add level3, gssoc and gssoc-ext labels

### CODE REVIEW

**Review by adarsh-singh01 — APPROVED** [review]

**Comment by adarsh-singh01** [comment]
@NK-Works kindly confirm.. Whether ur scores are being added or not from my repo

**Comment by NK-Works** [comment]
@adarsh-singh01 they are... because i cam across your project from the official gssoc project website

**Comment by NK-Works** [comment]
image
see this project is an official part of the gssoc

**Comment by adarsh-singh01** [comment]
Okay

**Pull request merged**
